openapi: 3.0.1
info:
  title: LogTest
  description: API Definition of API2
  version: 1.0.0
servers:
- url: http://localhost:8290/lognow
paths:
  /:
    get:
      responses:
        default:
          description: Default response
